TeamFile:
  special_index: $FILE_IN_FOLDER$#config\tactic
name:
  special_index: $INPUT_VERIFY$#character_name
position:
  select_items:
  - Main
  - Normal
  - Shield
  - Recovery
  - ''
vision:
  select_items:
  - Geo
  - Electro
  - Hydro
  - Pyro
  - Cryo
  - Dendro
  - Anemo
  - ''
n:
  type: int
priority:
  type: int
E_long_cd_time:
  type: float
E_short_cd_time:
  type: float
Elast_time:
  type: float
Epress_time:
  type: float
Qcd_time:
  type: float
Qlast_time:
  type: float
long_attack_time:
  type: float