Lang: 
  doc: 语言(language)
  annotation: 选择$locale$时，将根据系统语言自动选择。

BorderlessWindow:
  doc: 是否为无边框窗口
  annotation: 全屏或无边窗窗口化时设置为True，窗口化时设置为False。

DEBUG: 
 doc: 调试模式

CorrDegree:
  doc: 视角校准
  annotation: 秘境内视角校准时的辅助参数。若在秘境内视角偏左则增大该值，反之亦然。

DevicePaddle: 
  doc: paddle运算设备

DeviceTorch: 
  doc: torch运算设备
  annotation: yolox运算使用的设备,如果安装了cudnn则设为`'gpu'`(必须手动安装有cuda的pytorch。)，否则设为`'cpu'` 。 设置为`auto`时可以自动检测GPU可用性并自动切换。

Version: 
  doc: 版本

CaptureMode:
  doc: 截图模式

UsingAlphaChannel:
  doc: 是否使用透明度通道
  annotation: 如果的确无法使用BitBlt截图，设置为True。

CheckImport:
  doc: 是否在启动时检查导入

CloudGenshin:
  doc: 是否为云原神

DeterminingStrictWeight:
  doc: 检测裕度百分比
  annotation: 部分cv检测会使用该值。如果有些地方检测失败，可以尝试降低或提高该值。

InteractionMode:
  doc: 交互模式

Python32Path:
  doc: 32位python绝对路径
  annotation: 使用Dm模式时填写。

ChallengeTimes:
  doc:  秘境探险次数

FastMove:
  doc: 快速移动
  annotation: 当开启挑战时走过头时关闭。

IsObscuredDomain:
  doc:  是否为石化古树有被遮挡的副本

Resin: 
  doc: 树脂
  
AutoDistance:
  doc: 自动控距

AutoMove:
  doc: 自动移视角

Fps:
  doc: 识别频率 默认值：20

MaxNumberOfEnemyLoops:
  doc: 最大索敌次数 推荐值：130~160；默认值：150

ResetTime:
  doc: 索敌失败后冷却时间

DomainStageName:
  doc: 秘境关卡名
  annotation: 必须包含等级，等级必须为大写字母I。如果从秘境内启动则无需填写。当前版本可能有识别错误问题。

DomainName:
  doc: 秘境名
  annotation: 如果从秘境内启动则无需填写。

StartStop:
  doc: 功能启停

BlossomType:
  doc: 花朵类型

CollectionTimes:
  doc: 采集次数

