name: Synchronize Repository

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch'
        required: true
        default: 'main'
        type: choice
        options:
        - main
        - beta
        - dev
jobs:
    sync_repo:
        strategy:
            matrix:
                python-version: ["3.10"]
                os: [windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3.4.0
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4.5.0
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
            - name: Sync Repo
              run: |
                cd ../
                git clone https://github.com/infstellar/genshin_impact_assistant
                cd genshin_impact_assistant
                git submodule init
                git submodule update
                git checkout ${{ inputs.branch }} --
                python dev_tools/file_to_download.py
                cd ../GIA_Launcher_Download_Lib

            - name: Commit Changes
              run: |
                git push -f
                
